apiVersion: v1
kind: Secret
metadata:
  name: airflow-secrets
type: Opaque
data:
  # The sql_alchemy_conn value is a base64 encoded representation of this connection string:
  # postgresql+psycopg2://root:root@postgres-airflow:5432/airflow
  # use echo -n 'string' | base64 --- created by this command
  user: YWlyZmxvdw==
  password: YWlyZmxvdw==
  host: cG9zdGdyZXMtYWlyZmxvdw==